
.section .text.init, "ax", @progbits
.globl _init
_init:
    li s0, 0
    li s0, 1
    li s0, 2
    li s0, 3
    li s0, 4
    li s0, 5
    li s0, 6
    li s0, 7
    li s0, 8
    li s0, 9
    li s0, 10
    li s0, 11
    li s0, 12
    li s0, 13
    li s0, 14
    li s0, 15
    li s0, 16
    li s0, 17
    li s0, 18
    li s0, 19
    li s0, 20
    li s0, 21
    li s0, 22
    li s0, 23
